[build]
  base = "/frontend/client/"
  publish = "/frontend/client/build/"
  command = "npm run build"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200